# Generated by Django 2.0.8 on 2018-09-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=20, verbose_name='Badge Name')),
                ('cost', models.FloatField(default=0.0, verbose_name='Additional Cost')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convention_name', models.CharField(max_length=100, verbose_name='Convention Name')),
                ('convention_key', models.CharField(max_length=10, unique=True, verbose_name='Convention Key')),
                ('start_date', models.DateTimeField(verbose_name='Convention start time')),
                ('end_date', models.DateTimeField(verbose_name='Convention end time')),
                ('venue', models.CharField(max_length=100, verbose_name='Venue Name')),
                ('street_address', models.CharField(max_length=100, verbose_name='Street Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'convention',
                'verbose_name_plural': 'conventions',
                'ordering': ['-convention_name'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20, verbose_name='Day Name')),
                ('start_date', models.DateTimeField(verbose_name='Start time')),
                ('end_date', models.DateTimeField(verbose_name='End Time')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='con.Convention')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('game_system', models.CharField(max_length=70, verbose_name='Game System')),
                ('game_type', models.CharField(choices=[('Board', 'Board Game'), ('RolePlaying', 'Role-Playing'), ('CollectibleCard', 'Collectible Card'), ('LARP', 'LARP'), ('Seminar', 'Seminar')], max_length=20, verbose_name='Game Type')),
                ('additional_cost', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Additional Cost')),
                ('description', models.CharField(max_length=1200, verbose_name='Description')),
                ('short_description', models.CharField(max_length=200, verbose_name='Short Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='con.Convention')),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start time')),
                ('end_date', models.DateTimeField(verbose_name='End Time')),
                ('max_players', models.IntegerField(verbose_name='Maximum Players')),
                ('min_players', models.IntegerField(verbose_name='Minimum Players')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Room')),
                ('num_of_players', models.IntegerField(blank=True, default=0, null=True, verbose_name='Current Number of Players')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='con.Convention')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='con.Event')),
            ],
        ),
        migrations.AddIndex(
            model_name='convention',
            index=models.Index(fields=['convention_name'], name='con_convent_convent_4ff4e3_idx'),
        ),
        migrations.AddField(
            model_name='badge',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='con.Convention'),
        ),
    ]
