# Generated by Django 2.0.8 on 2018-09-08 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('con', '0002_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
