# Generated by Django 2.0.8 on 2018-09-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0003_eventschedule_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='players',
        ),
    ]
