# Generated by Django 2.0.8 on 2018-09-08 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('con', '0004_remove_eventschedule_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='gms',
            field=models.ManyToManyField(related_name='events_gming', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='event_schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
