# Generated by Django 2.0.8 on 2018-09-09 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0005_auto_20180908_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convention',
            options={'ordering': ['-name'], 'verbose_name': 'convention', 'verbose_name_plural': 'conventions'},
        ),
        migrations.RemoveIndex(
            model_name='convention',
            name='con_convent_convent_4ff4e3_idx',
        ),
        migrations.RenameField(
            model_name='convention',
            old_name='convention_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='convention',
            old_name='convention_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='con.Convention'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='con.Convention'),
        ),
        migrations.AddIndex(
            model_name='convention',
            index=models.Index(fields=['name'], name='con_convent_name_806f7a_idx'),
        ),
    ]
