# Generated by Django 2.0.8 on 2018-09-09 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0006_auto_20180909_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='convention',
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='gms',
            field=models.ManyToManyField(blank=True, related_name='events_gming', to=settings.AUTH_USER_MODEL),
        ),
    ]
