# Generated by Django 2.0.8 on 2018-09-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0007_auto_20180909_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventschedule',
            old_name='created_by',
            new_name='creator',
        ),
    ]
