# Generated by Django 2.0.8 on 2018-09-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0009_auto_20180911_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='con.TimeSlot'),
        ),
    ]
