# Generated by Django 2.0.8 on 2018-09-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0010_eventschedule_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='start_date',
            field=models.DateTimeField(blank=True, verbose_name='Start time'),
        ),
    ]
